# write Here ##########

SharedLibrary('EPG',['EPG.c'])
SharedLibrary('Tuner',['Tuner.c'])
SharedLibrary('MenuUI',['MenuUI.c'])
Program('tvmain',['tvmain.c'],LIBS=['EPG','Tuner','MenuUI'],LIBPATH='.')
#######################
#######################

