CC = gcc
OBJS = prog.o file1.o file2.o file3.o

# write Here ##########

#######################

prog : $(OBJS)
	$(CC) -o $@ $^

# write Here ##########

#######################


clean :
	rm $(OBJS)
	rm prog
